In [1]:
import torch



* arange(n) 으로 0,1 ... n-1 값을 갖는 새로운 텐서를 만들 수 있다. 디폴트 간격은 1이고, 달리 지정하지 않는 한 새 텐서는 메인 메모리에 저장되며 CPU 기반 계산을 위해 지정됨.



In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

* shape 으로 텐서의 shape 알 수 있고, numel()로 전체 element 개수를 알 수 있음. reshape 이용하여 shape 변경 가능(텐서가 자동으로 유추하기를 원하는 차원에 대해 -1을 배치할 수 있다)

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X = x.reshape(3, 4) # x.reshape(-1, 4) 또는 x.reshape(3, -1) 도 가능 
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

* zeros, ones 이용하여 0,1로 초기화된 텐서 선언 가능

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

* randn 이용하여 0 ~ 1 사이 랜덤 값으로 초기화 가능

In [8]:
torch.randn(3, 4)

tensor([[ 0.5325, -1.7591, -0.6913,  0.6396],
        [-0.7917, -0.1507,  0.6681, -1.5975],
        [-0.7905,  1.9196,  1.7223, -0.0711]])

* 특정 값으로 지정하여 초기화 가능

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])